#!/bin/bash
# Perform a synthetic upgrade from RHCOS 4.2; see
# https://github.com/coreos/coreos-assembler/pull/1012/commits/6ac1f1455ca158c1f0a6f530265a373912bcdbbe
# This is a relatively quick hack, we should clearly try to formalize this more and also
# get it in FCOS.

set -euo pipefail

if ! [ -d builds ]; then
    echo "Must be run from cosa build directory" 1>&2
    exit 1
fi

case "$(uname -m)" in 
    "x86_64")
        # This is from https://github.com/openshift/installer/blob/release-4.2/data/data/rhcos.json
        build_tag="rhcos-4.2"
        build_image="42.80.20191002.0"
        ;;
    "s390x")
        # s390x builds are in the here until they have an rhcos.json entry in the installer
        build_tag="rhcos-4.2-s390x"
        build_image="42s390x.81.20200224.0"
        ;;
    *)
        # 4.2 is not a supported release for other arches
        echo "Upgrade from 4.2 not supported for ${arch}"
        exit 1
esac

PREVIOUS_IMAGE=${PREVIOUS_IMAGE:-https://releases-art-rhcos.svc.ci.openshift.org/art/storage/releases/${build_tag}/${build_image}/rhcos-${build_image}-qemu.qcow2}
previmg=${PREVIOUS_IMAGE_PATH:-tmp/$(basename ${PREVIOUS_IMAGE})}
if ! [ -f "${previmg}" ]; then
    curl -L "${PREVIOUS_IMAGE}" | gunzip > "${previmg}"
fi

cosa offline-update "${previmg}"
kola run -p qemu-unpriv -b rhcos --ignition-version v2 --qemu-image "${previmg}" --output-dir tmp/kola-upgrade basic
echo "Upgrade test from 4.2 successful"
